baseURL = "ajulu.netlify.app"
languageCode = "en-us"
title = "Stephen Ajulu"
paginate = 6
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
copyright= "Stephen Ajulu"

[outputs]
home = ["HTML", "RSS", "JSON"]
[outputFormats.RSS]
baseName = "feed"
mediatype = "application/rss"
[outputFormats.JSON]
baseName = "feed"
mediatype = "application/json"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  twitter_handle = "@stephenajulu"
  creator = "stephenajulu"
  showAuthorOnHomepage = true
  showAuthorOnPosts = true
  showIntroContentOnHomepage = true
  showPostsOnHomepage = false
  usePaginationOnHomepage = false
  limitPostsOnHomepage = 3 # only used if usePaginationOnHomepage is false
  sortPostsByDateOldestFirst = false
  addDot = true
  addFrame = true
  highlightColor = '#6320d6'
  baseColor = "#ffffff"
  baseOffsetColor = "#eaeaea"
  headingColor = "#1c1b1d"
  textColor = "#4e5157"
  dotColor = "#6320d6"
  enableGoogleFonts = true 
  location = "Nairobi, Kenya"
  enableGitInfo = true
  googleFontsUrl = "https://fonts.googleapis.com/css2?family=Inter:wght@100..900&family=Newsreader:ital,opsz,wght@0,6..72,200..800;1,6..72,200..800&display=swap"
  fontFamilyHeading = "Newsreader"
  fontFamilyParagraph = "Inter"
  fontFamilyMonospace = "monospace"
  formspree = "https://formspree.io/f/alunje73@gmail.com"
  copyright = "Stephen Ajulu"
  showFullTextinJSONFeed = "true"
  image = "/images/socialimage.png"
  logo = "/images/logo.svg"
  strapline = "IT Professional, Web Designer, Writer and Consultant"


  [Author]
    name = "Stephen Ajulu"
    email  = "ajulu.b22uf@aleeas.com"
    url = "https://stephenajulu.com"
    image = "images/about.jpg"
    description = "Hello, I'm Stephen Ajulu, a tech expert, writer, and consultant with over a decade of experience. I build impactful products, brands, and solutions by using cutting-edge technology, insight, and marketing."

# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = "Blog"
    identifier = "blog"
    weight = 2
    url = "/posts/"
  [[menu.main]]
    name = "Projects"
    identifier = "projects"
    weight = 3
    url = "/projects/"
  [[menu.main]]
    name = "About"
    identifier = "about"
    weight = 4
    url = "/About/"
