baseURL = "/"
languageCode = "en-us"
title = "Stephen Ajulu"
paginate = 6
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
copyright= "Stephen Ajulu"

[outputs]
home = ["HTML", "RSS", "JSON"]
[outputFormats.RSS]
baseName = "feed"
mediatype = "application/rss"
[outputFormats.JSON]
baseName = "feed"
mediatype = "application/json"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  twitter_handle = "@stephenajulu"
  creator = "stephenajulu"
  showAuthorOnHomepage = false
  showAuthorOnPosts = true
  showIntroContentOnHomepage = true
  showPostsOnHomepage = true
  usePaginationOnHomepage = true
  limitPostsOnHomepage = 3 # only used if usePaginationOnHomepage is false
  sortPostsByDateOldestFirst = false
  addDot = true
  addFrame = true
  highlightColor = '#5f2ab5' #66320d6
  baseColor = "#0a0a0a" #111216 #111111
  baseOffsetColor = "#eaeaea"
  headingColor = "#ffffff" #1c1b1d
  textColor = "#ffffff" #4e5157
  dotColor = "#5f2ab5"
  enableGoogleFonts = true 
  location = "Nairobi, Kenya"
  enableGitInfo = true
  googleFontsUrl = "https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000&family=Newsreader:ital,opsz,wght@0,6..72,200..800;1,6..72,200..800&display=swap"
  fontFamilyHeading = "Newsreader"
  fontFamilyParagraph = "DM Sans"
  fontFamilyMonospace = "monospace"
  formspree = "https://formspree.io/f/alunje73@gmail.com"
  copyright = "Stephen Ajulu"
  showFullTextinJSONFeed = "true"
  image = "images/socialimage.png"
  logo = "images/logo.svg"


  [Author]
    name = "Stephen Ajulu"
    email  = "ajulu.b22uf@aleeas.com"
    url = "https://stephenajulu.com"
    image = "images/about.jpg"
    description = "Hello, I'm Stephen Ajulu, a seasoned tech expert, writer, and consultant with over a decade of experience. I build impactful products and solutions by using technology, design, and engineering  strategically."

# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = "Blog"
    identifier = "blog"
    weight = 2
    url = "/posts/"
  [[menu.main]]
    name = "About"
    identifier = "about"
    weight = 4
    url = "/About/"
